function importfile(Lagrange_Dynamics)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  Lagrange_Dynamics:  file to read

%  Auto-generated by MATLAB on 28-Feb-2013 20:54:52

% Import the file
newData1 = load('-mat', Lagrange_Dynamics);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end